### ISSUE TITLE
Peering Page does not show Incoming/Outgoing messages

### ISSUE THREAD

**Issue by WernerderChamp** [iotaledger/node-dashboard#12]
When clicking on the peers page, all peers show, but the amount of incoming/outgoing messages does not appear.

Browser: Brave V1.18.70
Hornet Version: chrysalis-pt2 commit 162b6a8
![image](https://user-images.githubusercontent.com/23498090/102322775-e4fb4100-3f7f-11eb-86f5-104b021123f3.png)

**Comment by obany** [comment]
This is not yet implemented

**Comment by obany** [comment]
Waiting on https://github.com/gohornet/hornet/issues/836

**Comment by obany** [comment]
Added in https://github.com/iotaledger/node-dashboard/commit/77bc011f98e9a4d1c918ba0f930024c62ef31a6e
