### ISSUE TITLE
More Peers shown in Dashboard than set in peering.json

### ISSUE THREAD

**Issue by MaKla89** [iotaledger/node-dashboard#13]
I have entered 4 static neighbors in the peering.json. After some time, the dashboard showed 5 peers. Not only was the 5th peer not entered by me, but it is also connected (green dot) according to the dashboard. See screenshot attached for details.

System: Hetzner VPS CX21, Ubuntu 20.04.1

![image](https://user-images.githubusercontent.com/33317175/102326823-2e01c400-3f85-11eb-9297-0bf050a1546a.png)

**Comment by svenger87** [comment]
I have the feeling the following is set to true in chrysalis-pt2 branch
https://github.com/gohornet/hornet/blob/0715a1633366b2a459f79098116050c37467b7a1/peering.json#L2

**Comment by MaKla89** [comment]
Reason found: Default config allows up to 4 unknown peers to be connected for gossip!
