### ISSUE TITLE
Shimmer Dashboard memory increase on MAC OS and iOS till break

### ISSUE THREAD

**Issue by MyMonk089** [iotaledger/node-dashboard#160]
## Bug description

When the Dashboard runs on "Home", it constantly uses around 190 MB of RAM. If I then go to the "Visualizer", it goes up to around 500 MB permanently. So far so good. 

But when I go back to "Home" AFTER being on the "Visualizer", it starts increasing memory usage by about 200 MB every few seconds. After 2-3 minutes is then at about 5 GB! RAM usage and the message comes up with the high memory consumption. If I don't refresh the page manually it crashes after some time.

## Node.js version

Which version of Node.js are you running?

- Node.js version: Don't know. How to check? Installed the node completely fresh yesterday with the wiki tutorial.

## Hardware specification

What hardware are you using?

- Operating system: MAC OS Ventura public BETA (V 13.0) or iOS 16 public BETA 
- RAM: 16 GB (MAC) 4 GB (iPhone)
- Cores: 10 core (MAC) 6 core (iPhone)
- Device:

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

see description upon. 

## Expected behaviour

Memory usage should stay at about the same levels all the time.

## Actual behaviour

Increase till it breaks. Maybe the bug is related in using BETA software??

## Errors

<img width="976" alt="Bildschirm­foto 2022-07-22 um 09 57 45" src="https://user-images.githubusercontent.com/60474745/180407717-2102c4ef-4ba2-467b-93d7-99dea05c59bc.png">
<img width="561" alt="Bildschirm­foto 2022-07-22 um 09 59 16" src="https://user-images.githubusercontent.com/60474745/180407723-4b742cdd-d170-4d0a-a82f-d48c8a361108.png">
<img width="1608" alt="Bildschirm­foto 2022-07-22 um 09 59 33" src="https://user-images.githubusercontent.com/60474745/180407725-19cece58-344e-4ea1-80c6-0f984fee223a.png">

**Comment by alexsporn** [comment]
Every time you switch to the visualizer, a new instance is probably created and when you switch away, it does not get cleaned up. This is easy to reproduce
@brancoder

**Comment by MyMonk089** [comment]
Yeah something like that. But I started with Home, then switched to visualiser and then only once back to Home and stayed there. The it increases as stated before. The normal value of the Home Screen (about 200 MB) increases every few seconds.

**Comment by brancoder** [comment]
@MyMonk089  
Could you please review this [PR](https://github.com/iotaledger/node-dashboard/pull/166) and check if it resolves the memory issue.

**Comment by MyMonk089** [comment]
@brancoder Hey. Cannot review, I am not a dev, but I can test the fix when its pushed.

**Comment by alexsporn** [comment]
@brancoder tested this locally and sadly this does not fix the increase in memory when switching from visualizer to explorer multiple times. Only a refresh clears up memory.
