### ISSUE TITLE
Show how many MS the node is behind

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/node-dashboard#17]
In the old dashboard if you hovered over the LSMI/LMI metric you could see the difference. This was really helpful to see if the node is catching up.

**Comment by obany** [comment]
This will be visible in the extended peer page which is not yet implemented

**Comment by obany** [comment]
Peer metrics page added https://github.com/iotaledger/node-dashboard/commit/54b73bc4a31fa0fbf418fb37c7f3d92557fc72ab

![image](https://user-images.githubusercontent.com/5030334/105720696-027add80-5f24-11eb-9c32-cf35381a385b.png)
