### ISSUE TITLE
Show if neighbors are unsync.

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/node-dashboard#18]
I think neighbors should have another color if they are connected, but not synced.
Maybe orange?
So it would be:
Red: Not connected
Orange: Connected but not synced
Green: Connected and Synced

**Comment by obany** [comment]
This can be achieved once this issue is done https://github.com/gohornet/hornet/issues/836

**Comment by Travetown** [comment]
So far, the neighbor nodes that are in an old network are also shown in green.  maybe they should be changed too.

**Comment by obany** [comment]
Added in https://github.com/iotaledger/node-dashboard/commit/77bc011f98e9a4d1c918ba0f930024c62ef31a6e
