### ISSUE TITLE
Make graphs more informative for node operators

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/node-dashboard#19]
I really like the look of the new dashboard. But sometimes it's hard to get useful information out of the graphs.
I don't know if these "bar" graphs are always the best solution. At least they should have a tooltip that shows the metric of the bar you hover over.
Also, the graphs under Analytics->Node for database size and memory would probably look better as simple graphs.

**Comment by obany** [comment]
The graphs design has now been improved with additional information and values next to each other instead of cumulative,

**Comment by Dr-Electron** [comment]
I think this issue should be opened again. I talked with a lot of people and it's really hard to get useful Information out of this graphs. I think we need more line graphs. And tooltips to show values if you hover over the graph. In my opinion we should prefer usability over design.

**Comment by muXxer** [comment]
Hey Martyn,
I also got a lot of feedback, and I also feel that same that we should use the line graphs from the old dashboard.
Even if the current bar graphs may look nice... they doesn't help at all if I want to use the dashboard to analyze stuff.
Maybe we can talk to the design team again about this?

**Comment by obany** [comment]
Sure, it only makes sense to have the graphs if they are actually useful :)

We should outline which graphs we want and how they should be displayed (timescales, format etc)

**Comment by msarcev** [comment]
Graphs removed in favour of Graphana.
