### ISSUE TITLE
Bee: visualizer seems to be broken in Testnet3

### ISSUE THREAD

**Issue by kranebitt** [iotaledger/node-dashboard#21]
![2BCEFC12-B5C0-4F89-A0DA-A8BC5569B147](https://user-images.githubusercontent.com/47479898/106802925-e41f8b00-6663-11eb-9a3f-042c80846d37.jpeg)

**Comment by muXxer** [comment]
Its not a dashboard issue, since it works on hornet. Please open a ticket at <https://github.com/iotaledger/bee>

**Comment by kranebitt** [comment]
Ok. Thank you.
