### ISSUE TITLE
[Task]: Implement PluginService in Participation and Spammer plugins

### ISSUE THREAD

**Issue by brancoder** [iotaledger/node-dashboard#225]
### Task description

Refactor Participation and Spammer plugins and implement Plugin Service to make plugin API calls similar to Poi plugin.

### Requirements

Plugin Service is implemented on branch created in this PR- https://github.com/iotaledger/node-dashboard/pull/224

### Acceptance criteria

Participation and Spammer plugins use Plugin Service

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by msarcev** [comment]
Closing task i favour of original one https://github.com/iotaledger/node-dashboard/issues/102
