### ISSUE TITLE
Updating neighbors via dashboard

### ISSUE THREAD

**Issue by no8ody** [iotaledger/node-dashboard#25]
I don't know if it would be easy to implement, however, in addition to managing the neighbors, it would be good if you could simply update a neighbor without having to delete and re-add it yourself.

The whole thing would still be a remove and re-add in the background, but a plus for usability.

**Comment by obany** [comment]
Added with https://github.com/iotaledger/node-dashboard/commit/bba58cc53d14dc2887a285a13d0aed802b0d8cb4
