### ISSUE TITLE
Increase Dashboard Graph Time Window

### ISSUE THREAD

**Issue by vuapo-eth** [iotaledger/node-dashboard#26]
The graphs on the dashboard are moving too fast. Comparing stats within the past 30 seconds is not really useful either.
Besides the visual overload, graphs are flactuating too much as they immediately rescale to a single spike and rescale once again seconds later as the spike leaves the window.

Please show stats from a larger time window and consolidate stats from 1 bar every second to larger time chunks to smoothen out the graph.

**Comment by msarcev** [comment]
Graphs removed from `v2.0.0-rc.1` in favour of Graphana.
