### ISSUE TITLE
LSMI / LMI in Peer overview should be CMI / LMI

### ISSUE THREAD

**Issue by TeeVeeEss** [iotaledger/node-dashboard#27]
As shown in the hornet dashboard: 
![image](https://user-images.githubusercontent.com/17521100/109861972-31d9e400-7c60-11eb-9a2d-7d8699eb5ca2.png)

https://github.com/iotaledger/node-dashboard/blob/b0524e88df5b893c15c4e1fbfac89b18e6845fda/src/app/routes/Peer.tsx#L248
Small issue, easy to fix ;)

**Comment by obany** [comment]
For peers that is correct, we only know LSMI from them
