### ISSUE TITLE
[Task]: Merge dependabot PRs

### ISSUE THREAD

**Issue by msarcev** [iotaledger/node-dashboard#289]
### Task description

Cleanup dependabot PRs

- Merge one by one an test (close the ones that break the build, if any)

### Requirements

N/A

### Acceptance criteria

N/A

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by brancoder** [comment]
Merged all open dependabot PRs
