### ISSUE TITLE
Remove log tab from the dashboard until we have data for it

### ISSUE THREAD

**Issue by WernerderChamp** [iotaledger/node-dashboard#32]
Currently the log tab only holds the placeholder "What should we show for the log?". As it does not look like logs will be added to this tab before chrysalis pt2 drops, I'd suggest to remove the tab for the release and bring it back once we have some data to display there.

![image](https://user-images.githubusercontent.com/23498090/113896517-4adb3500-97ca-11eb-8e7a-9cc8680fda81.png)

I have opened an issue over at the hornet repo with some suggestions what to put into the log tab: https://github.com/gohornet/hornet/issues/844

**Comment by obany** [comment]
Removed
