### ISSUE TITLE
Message per second graph incorrect scaling 

### ISSUE THREAD

**Issue by hristo-mavrodiev** [iotaledger/node-dashboard#37]
## Bug description

Only the scale bar of the graphic is updated [0-740] . The bars are with the same size after scale change.

![image](https://user-images.githubusercontent.com/61916767/116568775-71941380-a911-11eb-87af-f821cc7b82b9.png)

## Node.js version

Which version of Node.js are you running?

- Node.js version:

## Hardware specification

What hardware are you using?

- Operating system:Debian 10
- RAM:2gb
- Cores:2
- Device: google cloud server 

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. view the message per second graph on http://localhost:8081/analytics/tangle
2. 
3. 

## Expected behaviour
Both scale bar [0-740] and bars get scaled when needed.

## Actual behaviour
Only the scale bar [0-740] is updated

## Errors

Paste any errors that you see, including logs, errors, or screenshots.

**Comment by msarcev** [comment]
Outdated for v2.0.0-rc.1
