### ISSUE TITLE
Dashboard not always accessible with Safari

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/node-dashboard#41]
## Bug description

Sometime I have issues with Safari and opening the dashboard. It always switches between online and offline. And if it is shown as online most parameters are missing.

I use Hornet version 1.0.1.

MacOS Big Sure `11.3 (20E232)`

Tell me if I can provide further information.

<img width="1172" alt="bug_dash" src="https://user-images.githubusercontent.com/61637085/116828996-79b6b200-aba2-11eb-81ef-2d3cb2f2b0bb.png">

**Comment by obany** [comment]
Are there any errors logged on the dev tools?

**Comment by Dr-Electron** [comment]
Sorry for my late reply. I'm not familiar with the Safari dev tools. Where should I look?

**Comment by MyMonk089** [comment]
Still got the same problem. Can we provide any data for you obany? You just have to tell me where to look in the dev tools. Not experienced in this. Thx! Chrome on MacOS is working perfect btw. Only a Safari issue.

**Comment by msarcev** [comment]
We need to check if this is still the case with 2.0.0-rc.1.

**Comment by Dr-Electron** [comment]
Seems to be fine. I never had any problems in months 🤔
