### ISSUE TITLE
[feature-request] Adding health check on peers

### ISSUE THREAD

**Issue by hristo-mavrodiev** [iotaledger/node-dashboard#48]
## Description

There isn't a check for peers to be healthy. For example if your peer stuck at CLI/MLI index 552959 / 552959 there is a green light on it that it's synced.
![image](https://user-images.githubusercontent.com/61916767/124271650-6003fd80-db46-11eb-9cbe-cc5d86e493fe.png)

## Motivation
It's confusing to see a green light on your peers even if they are unhealty.

## Requirements

Write a list of what you want this feature to do.
Could add also a health status of the peer next to *Connected *Synced *Peers
![image](https://user-images.githubusercontent.com/61916767/124271963-cd179300-db46-11eb-8d32-b3c1ebbcf32a.png)
Also on the main peers tab to be show (yellow/red status)
![image](https://user-images.githubusercontent.com/61916767/124272563-93935780-db47-11eb-9aed-1a5df25462b9.png)

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

No.

**Comment by msarcev** [comment]
Is this still relevant for `v2.0.0-rc.1` ?

**Comment by msarcev** [comment]
We need to make sure that we take into account "our" node info about latest milestone vs "what peer is reporting".
This seams to be already the case in the code.
Test if this works, and close the task as outdated.

**Comment by msarcev** [comment]
Reproduce this (get the peer to be "stuck" ask Max), and if it already works we can close.

**Comment by brancoder** [comment]
This issue has been fixed:
- The indicator on Homepage is yellow if peer is unhealthy
- The indicator on Peer page is red if peer is not synced

Homepage:
![Image](https://user-images.githubusercontent.com/52735957/208087623-6e32005e-1fa6-4d43-8108-5c708bf8fba9.png)

Peer page:
![Image](https://user-images.githubusercontent.com/52735957/208088023-85a8aacb-f02d-4356-8108-bd6ca7c4224c.png)
