### ISSUE TITLE
The size of the window for CMI / LMI is not sufficient.

### ISSUE THREAD

**Issue by Travetown** [iotaledger/node-dashboard#57]
With some number combinations, the size of the window is no longer sufficient. It would be nice if an adjustment could be made.
<img width="325" alt="Bildschirmfoto 2021-12-17 um 08 53 13" src="https://user-images.githubusercontent.com/66588710/146509798-77976381-cc8b-4d47-931f-3e20509a3de7.png">

**Comment by msarcev** [comment]
Let's go with the solution of reducing the font of the second (less important information) to gain some space.
Additionally add a tooltip "on-hover" which always shows the full value.
![image](https://user-images.githubusercontent.com/6864498/197524889-2d14e741-ce8f-4c7b-a055-55ba7298cc26.png)
