### ISSUE TITLE
Dashboard login expires after 72 hours and causes UI glitches

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/node-dashboard#65]
## Bug description

Hornet Dashboard allows a login which shows the full UI. After 72 hours this login times out and the dashboard does not reflect this which causes UI glitches

 - Uptime is not correct
 - Peer Node status shows incorrectly
 - Perhaps other things not noticeable

The UI needs to handle this situation to prevent the Dashboard from showing incorrect information

![image](https://user-images.githubusercontent.com/44786846/163026886-f0267ca7-9a3d-4aec-9d27-d06c2167dfcd.png)

**Comment by msarcev** [comment]
Check if the is still relevant for `v2.0.0-rc.1`.
* What happens when the session times out ?
* Can we just loggout the user when session expires ?

**Comment by msarcev** [comment]
Refresh the token automatically before the session expires.
