### ISSUE TITLE
Displaying bug in "Analytics" Section after starting Node

### ISSUE THREAD

**Issue by Ohios089** [iotaledger/node-dashboard#8]
Each time after restarting the Node, there is an empty screen when clicking on "Analytics" for the first time. After a refresh everything is fine. This only happens in the "Analytics" Section, the others are fine from the beginning.

Please check it for a fix. Dr. Electron has the same Issue so I think it's a general bug.

Thx!

**Comment by Ohios089** [comment]
Today after a new restart of HORNET, every time when I click on "Analytics", there is an empty screen and a refresh needed.

**Comment by obany** [comment]
Could you add a screen grab and some additional details like browser, OS etc

**Comment by Ohios089** [comment]
![Bildschirmfoto 2020-12-17 um 14 57 26](https://user-images.githubusercontent.com/60474745/102496988-646c3b80-4078-11eb-837c-78d69f7e23e0.png)

**Comment by Ohios089** [comment]
MacOS Big Sur (11.1) with Safari Browser (14.0.2)

**Comment by obany** [comment]
This was already fixed a few days ago, hornet is linked to an older version of the node-dashboard.
